-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Setup monitors

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
    output   = "",
    mode     = "1920x1080",
    position = "0x0",
    scale    = 1,
})

-- monitor = DP-1, 1920x1080, 0x0, 1

hl.monitor({
    output   = "DP-2",
    mode     = "1920x1080",
    position = "0x-1080",
    scale    = 1,
})

--monitor = DP-2, 3840x2160@60, 1920x0, 1
-- Dual monitor example on G15 Strix
-- eDP-1 is the built in monitor while DP-1 is external
-- Both monitors here are at 1440 and 165Hz
-- DP-1 is on the left and  eDP-1 is on the right
--monitor=DP-1,2560x1440@165,0x0,1
--monitor=eDP-1,2560x1440@165,2560x0,1

-- hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("XDG_SESSION_TYPE", "wayland")
-- hl.env("GBM_BACKEND", "nvidia-drm")
-- hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})

-- Execute your favorite apps at launch

-- exec = swaybg -m fill -i ~/.config/hypr/wallpaper.png
-- exec = swaybg -m fill -i ~/.config/hypr/hong-kong-night.jpg

-- Source a file (multi-file configs)
-- source = ~/.config/hypr/myColors.conf

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.config({
    input = {
        kb_layout = "fr",
        kb_variant = "oss",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = false,
        },
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        repeat_rate = 50,
        repeat_delay = 200,
    },
})

hl.config({
    general = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        gaps_in = 4,
        gaps_out = 4,
        border_size = 4,
        -- col.active_border=rgb(8B0000)
        layout = "dwindle",
        col = {
            active_border = { colors = { "rgba(4B0000FF)", "rgba(FF0000FF)" }, angle = 195 },
            inactive_border = "rgba(595959FF)",
        },
    },
})

hl.config({
    misc = {
        disable_hyprland_logo = true,
    },
})

hl.config({
    decoration = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        blur = {
            enabled = true,
            size = 7,
            passes = 3,
        },
        --drop_shadow = yes
        --shadow_range = 4
        --shadow_render_power = 3
        --col.shadow = rgba(1a1a1aee)
    },
})

hl.config({
    animations = {
        enabled = true,
        -- Some default animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/ for more
        
    },
})

-- Courbes (bezier & spring), voir https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear",         { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear",   { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick",          { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.curve("easy", { type = "spring", mass = 1, stiffness = 265.2633, dampening = 25.8273644 })

-- Animations par leaf
hl.animation({ leaf = "global",     enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",     enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn",     enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",    enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "layers",     enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",    enabled = true, speed = 3,   spring = "easy" })  -- était 4.79
hl.animation({ leaf = "windowsIn",  enabled = true, speed = 2.5, spring = "easy", style = "popin 87%" })
hl.animation({ leaf = "fade",       enabled = true, speed = 2,   bezier = "quick" })

hl.config({
    dwindle = {
        -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        -- pseudotile option removed in recent Hyprland — toggle per-window via the `pseudo` dispatcher (mainMod + P)
        preserve_split = true,
        -- you probably want this
    },
})


-- See https://wiki.hyprland.org/Configuring/Keywords/#executing for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})



local mainMod = "SUPER"

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "Q", hl.dsp.exec_cmd("kitty"))

--open the terminal

hl.bind(mainMod .. " + " .. "code:36", hl.dsp.exec_cmd("kitty"))

--open the terminal

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "X", hl.dsp.window.close())

-- close the active window

hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("swaylock"))

-- Lock the screen

hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("wlogout --protocol layer-shell"))

-- show the logout window

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "M", hl.dsp.exit())

-- Exit Hyprland all together no (force quit Hyprland)

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("thunar"))

-- Show the graphical file browser

hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())

-- Allow a window to float

hl.bind(mainMod .. " + " .. "SPACE", hl.dsp.exec_cmd("wofi"))

-- Show the graphicall app launcher

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))

-- dwindle

--bind = $mainMod, S, exec, grim -g "$(slurp)" - | swappy -f - # take a screenshot

hl.bind(mainMod .. " + " .. "S", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh"))

-- ROG G15 Strix (2021) Specific binds

hl.bind("code:156", hl.dsp.exec_cmd("rog-control-center"))

-- ASUS Armory crate key

hl.bind("code:211", hl.dsp.exec_cmd("asusctl profile -n; pkill -SIGRTMIN+8 waybar"))

-- Fan Profile key switch between power profiles

hl.bind("code:121", hl.dsp.exec_cmd("pamixer -t"))

-- Speaker Mute FN+F1

hl.bind("code:122", hl.dsp.exec_cmd("pamixer -d 5"))

-- Volume lower key

hl.bind("code:123", hl.dsp.exec_cmd("pamixer -i 5"))

-- Volume Higher key

hl.bind("code:256", hl.dsp.exec_cmd("pamixer --default-source -t"))

-- Mic mute key

hl.bind("code:232", hl.dsp.exec_cmd("brightnessctl set 10%-"))

-- Screen brightness down FN+F7

hl.bind("code:233", hl.dsp.exec_cmd("brightnessctl set 10%+"))

-- Screen brightness up FN+F8

hl.bind("code:237", hl.dsp.exec_cmd("brightnessctl -d asus::kbd_backlight set 33%-"))

-- Keyboard brightness down FN+F2

hl.bind("code:238", hl.dsp.exec_cmd("brightnessctl -d asus::kbd_backlight set 33%+"))

-- Keyboard brightnes up FN+F3

hl.bind("code:210", hl.dsp.exec_cmd("asusctl led-mode -n"))

-- Switch keyboard RGB profile FN+F4

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. "code:10", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. "code:11", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. "code:12", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. "code:13", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. "code:14", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. "code:15", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. "code:16", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. "code:17", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + " .. "code:18", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + " .. "code:19", hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:10", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:11", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:12", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:13", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:14", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:15", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:16", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:17", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:18", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:19", hl.dsp.window.move({ workspace = 10 }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- LMB

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

-- RMB

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind("SUPER" .. " + " .. "O", hl.dsp.dpms("on"))

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("~/.config/hypr/xdg-portal-hyprland")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaybg -m fill -i ~/.config/hypr/background_images/mark-of-sacrifice-blurred.png")
end)

-- Exec (run every reload)
-- hl.on("config.reloaded", function()
--    hl.exec_cmd("swaybg -m fill -i ~/.config/hypr/background_images/mark-of-sacrifice-blurred.png")
-- end)
